import { randomUUID } from 'expo-crypto';
import { router } from 'expo-router';
import { useMemo, useState } from 'react';
import { ActivityIndicator, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { useSession } from '@/auth/session';
import { colors } from '@/constants/theme';
import { cents, type Outcome } from '@/lib/gate';
import { placeOrder } from '@/lib/backspace-api';

export function TradeTicket({ outcomes, acceptingOrders }: { outcomes: Outcome[]; acceptingOrders: boolean }) {
  const session = useSession(); const [selectedId, setSelectedId] = useState(outcomes[0]?.id); const [amount, setAmount] = useState('10'); const [reviewing, setReviewing] = useState(false); const [submitting, setSubmitting] = useState(false); const [message, setMessage] = useState<string | null>(null);
  const selected = outcomes.find((outcome) => outcome.id === selectedId) ?? outcomes[0];
  const dollars = Number(amount); const estimatedShares = useMemo(() => selected?.price && dollars > 0 ? dollars / selected.price : null, [dollars, selected?.price]);
  async function act() {
    if (!session.user) { router.push('/sign-in' as never); return; }
    if (!reviewing) { setReviewing(true); setMessage(null); return; }
    if (!selected || !Number.isFinite(dollars) || dollars <= 0) return;
    setSubmitting(true); setMessage(null);
    try {
      const result = await placeOrder({ tokenId: selected.id, side: 'BUY', totalCost: dollars.toFixed(2), orderType: 'MARKET', clientOrderId: randomUUID() }, session.getAccessToken);
      setMessage(`Order ${result.status.toLowerCase()}.`); setReviewing(false);
    } catch (error) { setMessage(error instanceof Error ? error.message : 'Order could not be submitted.'); }
    finally { setSubmitting(false); }
  }
  return <View style={styles.root}><View style={styles.heading}><Text style={styles.title}>Trade</Text><View style={styles.badge}><Text style={styles.badgeText}>GATE</Text></View></View><Text style={styles.label}>Choose an outcome</Text><View style={styles.outcomes}>{outcomes.map((outcome) => <Pressable key={outcome.id} onPress={() => { setSelectedId(outcome.id); setReviewing(false); }} style={[styles.outcome, selected?.id === outcome.id && styles.outcomeSelected]}><Text style={[styles.outcomeName, selected?.id === outcome.id && styles.outcomeNameSelected]}>{outcome.label}</Text><Text style={styles.outcomePrice}>{cents(outcome.price)}</Text></Pressable>)}</View><Text style={styles.label}>Amount</Text><View style={styles.amount}><Text style={styles.dollar}>$</Text><TextInput keyboardType="decimal-pad" onChangeText={(value) => { setAmount(value); setReviewing(false); }} style={styles.input} value={amount} /></View><View style={styles.estimate}><Text style={styles.estimateLabel}>Estimated shares</Text><Text style={styles.estimateValue}>{estimatedShares ? estimatedShares.toFixed(2) : '—'}</Text></View>{reviewing ? <View style={styles.review}><Text style={styles.reviewTitle}>Review order</Text><Text style={styles.reviewText}>Buy about {estimatedShares?.toFixed(2) ?? '—'} {selected?.label} shares for ${dollars.toFixed(2)}. Market execution can move the final price.</Text></View> : null}<Pressable disabled={!acceptingOrders || submitting || !selected || !(dollars > 0)} onPress={act} style={({ pressed }) => [styles.button, pressed && styles.pressed, (!acceptingOrders || submitting || !(dollars > 0)) && styles.disabled]}>{submitting ? <ActivityIndicator color={colors.ink} /> : <Text style={styles.buttonText}>{session.user ? reviewing ? 'Place order' : 'Review order' : 'Sign in to trade'}</Text>}</Pressable>{!acceptingOrders ? <Text style={styles.message}>This market is not accepting orders.</Text> : message ? <Text style={styles.message}>{message}</Text> : <Text style={styles.note}>Orders use your Backspace session. Gate credentials stay server-side.</Text>}</View>;
}
const styles = StyleSheet.create({ root: { backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.line, borderRadius: 18, padding: 15 }, heading: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 16 }, title: { color: colors.ink, fontSize: 18, fontWeight: '800' }, badge: { backgroundColor: colors.brandSoft, borderRadius: 999, paddingHorizontal: 9, paddingVertical: 5 }, badgeText: { color: colors.brand2, fontSize: 9, fontWeight: '900', letterSpacing: 0.7 }, label: { color: colors.ink3, fontSize: 10, fontWeight: '800', letterSpacing: 0.7, marginBottom: 8, textTransform: 'uppercase' }, outcomes: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 16 }, outcome: { flexGrow: 1, minWidth: 100, flexDirection: 'row', justifyContent: 'space-between', borderWidth: 1, borderColor: colors.line, backgroundColor: colors.canvasRaised, borderRadius: 12, padding: 12 }, outcomeSelected: { borderColor: colors.brand2, backgroundColor: colors.brandSoft }, outcomeName: { color: colors.ink2, fontSize: 13, fontWeight: '700' }, outcomeNameSelected: { color: colors.ink }, outcomePrice: { color: colors.green2, fontSize: 13, fontWeight: '800' }, amount: { flexDirection: 'row', alignItems: 'center', height: 56, borderRadius: 14, borderWidth: 1, borderColor: colors.lineStrong, backgroundColor: colors.canvasRaised, paddingHorizontal: 15 }, dollar: { color: colors.ink3, fontSize: 22, fontWeight: '700' }, input: { flex: 1, color: colors.ink, fontSize: 24, fontWeight: '800', paddingHorizontal: 8 }, estimate: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 12 }, estimateLabel: { color: colors.ink3, fontSize: 12 }, estimateValue: { color: colors.ink2, fontSize: 12, fontWeight: '700' }, review: { backgroundColor: colors.canvasRaised, borderRadius: 12, padding: 12, marginBottom: 12 }, reviewTitle: { color: colors.ink, fontSize: 12, fontWeight: '800' }, reviewText: { color: colors.ink3, fontSize: 11, lineHeight: 17, marginTop: 4 }, button: { minHeight: 52, borderRadius: 14, backgroundColor: colors.brand, alignItems: 'center', justifyContent: 'center' }, buttonText: { color: colors.ink, fontSize: 14, fontWeight: '800' }, pressed: { opacity: 0.84 }, disabled: { opacity: 0.45 }, note: { color: colors.ink3, fontSize: 9.5, textAlign: 'center', marginTop: 10 }, message: { color: colors.ink2, fontSize: 11, textAlign: 'center', lineHeight: 17, marginTop: 10 } });
