import { LinearGradient } from 'expo-linear-gradient';
import { router } from 'expo-router';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { BrandHeader } from '@/components/brand-header';
import { ChevronRightIcon, MarketsIcon, SparkIcon } from '@/components/icons';
import { colors } from '@/constants/theme';
export default function HomeScreen() { const insets = useSafeAreaInsets(); return <View style={[styles.screen, { paddingTop: insets.top }]}><BrandHeader /><ScrollView contentContainerStyle={styles.content}><LinearGradient colors={['rgba(88,34,251,0.32)', colors.surface]} style={styles.hero}><View style={styles.eyebrow}><SparkIcon width={16} height={16} color={colors.brand2} /><Text style={styles.eyebrowText}>BACKSPACE IS BEING BUILT</Text></View><Text style={styles.title}>Markets meet the conversation.</Text><Text style={styles.copy}>A native social experience where live outcomes, ideas, and reputation live together.</Text><Pressable onPress={() => router.push('/(tabs)/markets')} style={styles.button}><Text style={styles.buttonText}>Explore live markets</Text><ChevronRightIcon width={18} height={18} color={colors.ink} /></Pressable></LinearGradient><Text style={styles.heading}>What’s taking shape</Text><View style={styles.feature}><View style={styles.icon}><MarketsIcon color={colors.brand2} /></View><View style={styles.featureCopy}><Text style={styles.featureTitle}>Gate-powered markets</Text><Text style={styles.featureBody}>Live events, prices, depth, trades, and settlement data, inside Backspace.</Text></View></View><View style={styles.post}><View style={styles.avatar}><Text style={styles.avatarText}>B</Text></View><View style={styles.postCopy}><Text style={styles.postName}>Backspace <Text style={styles.handle}>@backspace</Text></Text><Text style={styles.postBody}>The next version of social should show who was early, what they believed, and how the market moved.</Text><View style={styles.postMarket}><Text style={styles.postMarketTitle}>Live markets are now available</Text><Text style={styles.postMarketAction}>View Markets →</Text></View></View></View></ScrollView></View>; }
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: colors.canvas }, content: { padding: 16, paddingBottom: 120, gap: 16 }, hero: { borderWidth: 1, borderColor: colors.line, borderRadius: 22, padding: 22 }, eyebrow: { flexDirection: 'row', gap: 8, alignItems: 'center' }, eyebrowText: { color: colors.brand2, fontSize: 10, fontWeight: '800', letterSpacing: 0.7 }, title: { color: colors.ink, fontSize: 34, lineHeight: 37, fontWeight: '900', letterSpacing: -1.3, marginTop: 20 }, copy: { color: colors.ink2, fontSize: 15, lineHeight: 23, marginTop: 12 }, button: { alignSelf: 'flex-start', flexDirection: 'row', alignItems: 'center', gap: 7, backgroundColor: colors.brand, borderRadius: 999, paddingHorizontal: 17, paddingVertical: 12, marginTop: 22 }, buttonText: { color: colors.ink, fontSize: 13, fontWeight: '800' }, heading: { color: colors.ink, fontSize: 17, fontWeight: '800', marginTop: 8 }, feature: { flexDirection: 'row', gap: 13, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.line, borderRadius: 18, padding: 16 }, icon: { width: 42, height: 42, borderRadius: 13, backgroundColor: colors.brandSoft, alignItems: 'center', justifyContent: 'center' }, featureCopy: { flex: 1 }, featureTitle: { color: colors.ink, fontSize: 15, fontWeight: '800' }, featureBody: { color: colors.ink2, fontSize: 13, lineHeight: 19, marginTop: 5 }, post: { flexDirection: 'row', gap: 11, borderTopWidth: 1, borderBottomWidth: 1, borderColor: colors.line, paddingVertical: 16 }, avatar: { width: 40, height: 40, borderRadius: 20, backgroundColor: colors.brand, alignItems: 'center', justifyContent: 'center' }, avatarText: { color: colors.ink, fontWeight: '900' }, postCopy: { flex: 1 }, postName: { color: colors.ink, fontWeight: '800' }, handle: { color: colors.ink3, fontWeight: '500' }, postBody: { color: colors.ink, fontSize: 14, lineHeight: 20, marginTop: 7 }, postMarket: { backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.line, borderRadius: 13, padding: 12, marginTop: 12 }, postMarketTitle: { color: colors.ink, fontSize: 13, fontWeight: '700' }, postMarketAction: { color: colors.brand2, fontSize: 12, fontWeight: '700', marginTop: 7 } });
