import { useQuery } from '@tanstack/react-query';
import { LinearGradient } from 'expo-linear-gradient';
import { useMemo, useState } from 'react';
import { FlatList, RefreshControl, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { BrandHeader } from '@/components/brand-header';
import { EventCard, MarketCard } from '@/components/market-card';
import { EmptyState, LoadingState } from '@/components/screen-state';
import { SearchIcon } from '@/components/icons';
import { colors } from '@/constants/theme';
import { groupMarkets, listMarkets, type EventGroup } from '@/lib/gate';

export default function MarketsScreen() {
  const insets = useSafeAreaInsets(); const [query, setQuery] = useState(''); const marketQuery = useQuery({ queryKey: ['gate-markets'], queryFn: listMarkets, refetchInterval: 60_000 });
  const groups = useMemo(() => { const needle = query.trim().toLowerCase(); return groupMarkets((marketQuery.data ?? []).filter((market) => !needle || `${market.question} ${market.eventTitle ?? ''} ${market.category}`.toLowerCase().includes(needle))); }, [marketQuery.data, query]);
  if (marketQuery.isLoading) return <View style={[styles.screen, { paddingTop: insets.top }]}><BrandHeader section="Markets" /><LoadingState label="Loading Gate markets" /></View>;
  if (marketQuery.isError) return <View style={[styles.screen, { paddingTop: insets.top }]}><BrandHeader section="Markets" /><EmptyState title="Markets are unavailable" message="We couldn't reach Gate's live catalog." onRetry={() => marketQuery.refetch()} /></View>;
  return <View style={[styles.screen, { paddingTop: insets.top }]}><BrandHeader section="Markets" /><FlatList data={groups} keyExtractor={(item) => item.id} contentContainerStyle={styles.content} keyboardDismissMode="on-drag" refreshControl={<RefreshControl refreshing={marketQuery.isRefetching} onRefresh={() => marketQuery.refetch()} tintColor={colors.brand2} />} ListHeaderComponent={<Header query={query} setQuery={setQuery} groups={groups} />} renderItem={({ item }) => item.markets.length > 1 ? <EventCard event={item} /> : <MarketCard market={item.markets[0]} />} ItemSeparatorComponent={() => <View style={styles.gap} />} ListEmptyComponent={<EmptyState title="No live markets found" message="Try a different search." />} /></View>;
}
function Header({ query, setQuery, groups }: { query: string; setQuery: (value: string) => void; groups: EventGroup[] }) {
  const trending = groups.slice(0, 6);
  return <View><LinearGradient colors={['rgba(88,34,251,0.28)', colors.surface, colors.surface]} style={styles.hero}><View style={styles.live}><View style={styles.dot} /><Text style={styles.liveText}>LIVE GATE MARKETS</Text></View><Text style={styles.heroTitle}>Trade what happens next.</Text><Text style={styles.heroCopy}>Follow live probabilities, market depth, and the conversations around every outcome.</Text></LinearGradient>
    {trending.length ? <><View style={styles.sectionRow}><Text style={styles.sectionTitle}>Trending now</Text><Text style={styles.sectionMeta}>BY LIVE VOLUME</Text></View><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.trending}>{trending.map((event) => <View key={event.id} style={styles.trendingCard}><Text style={styles.trendingCategory}>{event.category}</Text><Text style={styles.trendingTitle} numberOfLines={3}>{event.title}</Text><Text style={styles.trendingCount}>{event.markets.length} live {event.markets.length === 1 ? 'market' : 'markets'}</Text></View>)}</ScrollView></> : null}
    <View style={styles.search}><SearchIcon width={19} height={19} color={colors.ink3} /><TextInput value={query} onChangeText={setQuery} placeholder="Search markets and events" placeholderTextColor={colors.ink3} style={styles.input} returnKeyType="search" autoCorrect={false} /></View><View style={styles.sectionRow}><Text style={styles.sectionTitle}>{query ? 'Search results' : 'All events'}</Text><Text style={styles.sectionMeta}>{groups.length} LIVE</Text></View></View>;
}
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: colors.canvas }, content: { padding: 16, paddingBottom: 120 }, hero: { borderWidth: 1, borderColor: colors.line, borderRadius: 20, padding: 20, overflow: 'hidden' }, live: { alignSelf: 'flex-start', flexDirection: 'row', alignItems: 'center', gap: 7, backgroundColor: colors.brandSoft, borderRadius: 999, paddingHorizontal: 10, paddingVertical: 6, marginBottom: 18 }, dot: { width: 7, height: 7, borderRadius: 4, backgroundColor: colors.green2 }, liveText: { color: colors.brand2, fontSize: 10, fontWeight: '800', letterSpacing: 0.8 }, heroTitle: { color: colors.ink, fontSize: 30, lineHeight: 33, fontWeight: '800', letterSpacing: -1.1 }, heroCopy: { color: colors.ink2, fontSize: 14, lineHeight: 21, marginTop: 10 }, sectionRow: { flexDirection: 'row', alignItems: 'baseline', justifyContent: 'space-between', marginTop: 22, marginBottom: 11 }, sectionTitle: { color: colors.ink, fontSize: 16, fontWeight: '800' }, sectionMeta: { color: colors.ink3, fontSize: 10, fontWeight: '700', letterSpacing: 0.6 }, trending: { gap: 10, paddingRight: 8 }, trendingCard: { width: 210, minHeight: 126, backgroundColor: colors.surface, borderRadius: 16, borderWidth: 1, borderColor: colors.line, padding: 14 }, trendingCategory: { color: colors.brand2, fontSize: 9, fontWeight: '800', textTransform: 'uppercase', letterSpacing: 0.6 }, trendingTitle: { color: colors.ink, fontSize: 14, lineHeight: 19, fontWeight: '700', marginTop: 8 }, trendingCount: { color: colors.ink3, fontSize: 11, marginTop: 'auto', paddingTop: 9 }, search: { height: 48, flexDirection: 'row', alignItems: 'center', gap: 10, marginTop: 22, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.lineStrong, borderRadius: 14, paddingHorizontal: 14 }, input: { flex: 1, color: colors.ink, fontSize: 15, paddingVertical: 0 }, gap: { height: 12 } });
