import { useQuery } from '@tanstack/react-query';
import { router } from 'expo-router';
import { Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useSession } from '@/auth/session';
import { BrandHeader } from '@/components/brand-header';
import { BagIcon } from '@/components/icons';
import { LoadingState } from '@/components/screen-state';
import { colors } from '@/constants/theme';
import { ApiError, getPortfolio, type PortfolioPosition } from '@/lib/backspace-api';

export default function PortfolioScreen() {
  const insets = useSafeAreaInsets(); const session = useSession();
  const query = useQuery({ queryKey: ['gate-portfolio', session.user?.id], queryFn: () => getPortfolio(session.getAccessToken), enabled: Boolean(session.user), refetchInterval: 20_000, retry: (count, error) => !(error instanceof ApiError && error.status < 500) && count < 2 });
  if (!session.ready) return <Shell top={insets.top}><LoadingState label="Restoring your account" /></Shell>;
  if (!session.user) return <Shell top={insets.top}><View style={styles.center}><View style={styles.icon}><BagIcon color={colors.brand2} /></View><Text style={styles.title}>Your positions, in one place</Text><Text style={styles.copy}>Sign in to see live Gate balances, positions, open orders, trades, and claims.</Text><Pressable onPress={() => router.push('/sign-in' as never)} style={styles.button}><Text style={styles.buttonText}>Sign in to continue</Text></Pressable></View></Shell>;
  if (query.isLoading) return <Shell top={insets.top}><LoadingState label="Loading your live Gate account" /></Shell>;
  if (!query.data) return <Shell top={insets.top}><View style={styles.center}><View style={styles.pending}><Text style={styles.pendingText}>GATE BUILDER</Text></View><Text style={styles.title}>Account connection is ready for activation</Text><Text style={styles.copy}>{query.error instanceof Error ? query.error.message : 'Backspace sign-in is connected. Gate Builder still needs to enable the private account gateway before balances and trading can go live.'}</Text><Pressable onPress={() => query.refetch()} style={styles.secondary}><Text style={styles.secondaryText}>Check again</Text></Pressable></View></Shell>;
  const data = query.data;
  return <Shell top={insets.top}><ScrollView refreshControl={<RefreshControl tintColor={colors.brand2} refreshing={query.isRefetching} onRefresh={() => query.refetch()} />} contentContainerStyle={styles.content}><Text style={styles.eyebrow}>TOTAL MARKET VALUE</Text><Text style={styles.balance}>{usd(data.total)}</Text><Text style={[styles.pnl, { color: data.dailyPnl >= 0 ? colors.green2 : colors.pink2 }]}>{data.dailyPnl >= 0 ? '+' : ''}{usd(data.dailyPnl)} today</Text><View style={styles.stats}><Stat label="Positions" value={usd(data.positionValue)} /><Stat label="Available" value={usd(data.available)} /><Stat label="Claimable" value={usd(data.unclaimed)} /></View><Text style={styles.sectionTitle}>Open positions</Text>{data.positions.length ? data.positions.map((position) => <Position key={position.positionId} position={position} />) : <View style={styles.empty}><Text style={styles.emptyTitle}>No open positions</Text><Text style={styles.emptyText}>Explore a live market to make your first call.</Text></View>}<Text style={styles.liveNote}>Pulled live from Gate. Backspace does not store a portfolio copy.</Text></ScrollView></Shell>;
}
function Shell({ top, children }: { top: number; children: React.ReactNode }) { return <View style={[styles.screen, { paddingTop: top }]}><BrandHeader section="Portfolio" />{children}</View>; }
function Stat({ label, value }: { label: string; value: string }) { return <View style={styles.stat}><Text style={styles.statLabel}>{label}</Text><Text style={styles.statValue}>{value}</Text></View>; }
function Position({ position }: { position: PortfolioPosition }) { return <View style={styles.position}><View style={styles.positionTop}><View><Text style={styles.outcome}>{position.outcome}</Text><Text style={styles.positionMeta}>{trim(position.size)} shares · {Math.round(position.averagePrice * 100)}¢ avg</Text></View><Text style={styles.positionValue}>{usd(position.value)}</Text></View><View style={styles.positionBottom}><Text style={styles.settlement}>{position.settlementStatus}</Text>{position.claimableAmount > 0 ? <Text style={styles.claim}>Claim {usd(position.claimableAmount)}</Text> : null}</View></View>; }
function usd(value: number) { return new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 2 }).format(value); }
function trim(value: number) { return new Intl.NumberFormat('en-US', { maximumFractionDigits: 4 }).format(value); }
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: colors.canvas }, center: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 34, paddingBottom: 110 }, icon: { width: 60, height: 60, borderRadius: 19, backgroundColor: colors.brandSoft, alignItems: 'center', justifyContent: 'center' }, title: { color: colors.ink, fontSize: 22, fontWeight: '800', textAlign: 'center', marginTop: 18 }, copy: { color: colors.ink3, fontSize: 14, lineHeight: 21, textAlign: 'center', marginTop: 10, maxWidth: 360 }, button: { backgroundColor: colors.brand, borderRadius: 16, paddingHorizontal: 22, paddingVertical: 15, marginTop: 24 }, buttonText: { color: colors.ink, fontWeight: '800' }, secondary: { borderRadius: 14, borderWidth: 1, borderColor: colors.lineStrong, paddingHorizontal: 20, paddingVertical: 12, marginTop: 22 }, secondaryText: { color: colors.ink2, fontWeight: '700' }, pending: { backgroundColor: colors.brandSoft, borderRadius: 999, paddingHorizontal: 12, paddingVertical: 7 }, pendingText: { color: colors.brand2, fontSize: 10, fontWeight: '900', letterSpacing: 0.9 }, content: { padding: 18, paddingBottom: 120 }, eyebrow: { color: colors.ink3, fontSize: 10, fontWeight: '800', letterSpacing: 0.9 }, balance: { color: colors.ink, fontSize: 39, fontWeight: '900', letterSpacing: -1.4, marginTop: 7 }, pnl: { fontSize: 13, fontWeight: '700', marginTop: 4 }, stats: { flexDirection: 'row', gap: 8, marginTop: 24 }, stat: { flex: 1, backgroundColor: colors.surface, borderRadius: 15, borderWidth: 1, borderColor: colors.line, padding: 12 }, statLabel: { color: colors.ink3, fontSize: 9, fontWeight: '700' }, statValue: { color: colors.ink, fontSize: 14, fontWeight: '800', marginTop: 7 }, sectionTitle: { color: colors.ink, fontSize: 19, fontWeight: '800', marginTop: 28, marginBottom: 12 }, position: { backgroundColor: colors.surface, borderRadius: 17, borderWidth: 1, borderColor: colors.line, padding: 15, marginBottom: 10 }, positionTop: { flexDirection: 'row', justifyContent: 'space-between', gap: 12 }, outcome: { color: colors.ink, fontSize: 15, fontWeight: '800' }, positionMeta: { color: colors.ink3, fontSize: 11, marginTop: 5 }, positionValue: { color: colors.ink, fontSize: 16, fontWeight: '800' }, positionBottom: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 14, paddingTop: 11, borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: colors.line }, settlement: { color: colors.ink3, fontSize: 10, fontWeight: '700' }, claim: { color: colors.green2, fontSize: 11, fontWeight: '800' }, empty: { backgroundColor: colors.surface, borderRadius: 17, borderWidth: 1, borderColor: colors.line, padding: 24, alignItems: 'center' }, emptyTitle: { color: colors.ink, fontWeight: '800' }, emptyText: { color: colors.ink3, fontSize: 12, marginTop: 5 }, liveNote: { color: colors.ink3, fontSize: 10, textAlign: 'center', marginTop: 22 } });
