import { router } from 'expo-router';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useSession } from '@/auth/session';
import { BrandHeader } from '@/components/brand-header';
import { colors } from '@/constants/theme';

export default function ProfileScreen() {
  const insets = useSafeAreaInsets(); const session = useSession();
  const label = session.user?.email || session.user?.id || 'Backspace member';
  return <View style={[styles.screen, { paddingTop: insets.top }]}><BrandHeader section="Profile" /><View style={styles.body}><View style={styles.avatar}><Text style={styles.avatarText}>{session.user ? label.slice(0, 1).toUpperCase() : 'B'}</Text></View>{session.user ? <><Text style={styles.title}>You’re signed in</Text><Text style={styles.handle} numberOfLines={1}>{label}</Text><Text style={styles.copy}>Your social identity and market record will stay connected across Backspace.</Text><View style={styles.status}><View style={styles.dot} /><View style={styles.statusCopy}><Text style={styles.statusTitle}>Backspace session secured</Text><Text style={styles.statusText}>Gate credentials never live on this device.</Text></View></View><Pressable onPress={() => session.logout()} style={styles.secondary}><Text style={styles.secondaryText}>Sign out</Text></Pressable></> : <><Text style={styles.title}>Your Backspace identity</Text><Text style={styles.copy}>Sign in to post, follow people, track your calls, and access your market account.</Text><Pressable onPress={() => router.push('/sign-in' as never)} style={styles.button}><Text style={styles.buttonText}>Sign in or create account</Text></Pressable></>}</View></View>;
}
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: colors.canvas }, body: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 30, paddingBottom: 110 }, avatar: { width: 76, height: 76, borderRadius: 38, backgroundColor: colors.brand, alignItems: 'center', justifyContent: 'center' }, avatarText: { color: colors.ink, fontSize: 27, fontWeight: '900' }, title: { color: colors.ink, fontSize: 23, fontWeight: '800', textAlign: 'center', marginTop: 19 }, handle: { color: colors.brand2, fontSize: 14, fontWeight: '700', maxWidth: 290, marginTop: 7 }, copy: { color: colors.ink3, fontSize: 14, lineHeight: 21, textAlign: 'center', marginTop: 10, maxWidth: 350 }, button: { backgroundColor: colors.brand, borderRadius: 16, paddingHorizontal: 22, paddingVertical: 15, marginTop: 24, minWidth: 230, alignItems: 'center' }, buttonText: { color: colors.ink, fontWeight: '800' }, status: { width: '100%', flexDirection: 'row', alignItems: 'center', gap: 12, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.line, borderRadius: 16, padding: 14, marginTop: 22 }, dot: { width: 10, height: 10, borderRadius: 5, backgroundColor: colors.green2 }, statusCopy: { flex: 1 }, statusTitle: { color: colors.ink, fontSize: 13, fontWeight: '800' }, statusText: { color: colors.ink3, fontSize: 11, marginTop: 3 }, secondary: { marginTop: 20, borderRadius: 14, borderWidth: 1, borderColor: colors.lineStrong, paddingHorizontal: 22, paddingVertical: 12 }, secondaryText: { color: colors.ink2, fontWeight: '700' } });
